name: Run Python Script Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # This cron schedule runs the workflow every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Python script
        env:
          ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: |
          python upload_videos.py
